export interface PartyPromise {
  text: string;
  category: string;
  isPro: boolean;
  status?: string;
}

export const PS_PROGRAM_NAME = "TRESK! — Totálny reštart Slovenska";

export const PS_PROMISES: PartyPromise[] = [
  // Ekonomika a inovácie (20)
  { text: "Zrušenie dane z finančných transakcií, ktorá trestá úspešné firmy a brzdí ekonomiku", category: "Ekonomika", isPro: true },
  { text: "Reforma ByroKAT — zníženie byrokratickej záťaže podnikateľov aspoň o tretinu", category: "Ekonomika", isPro: true },
  { text: "Zníženie zdanenia práce — presun daňového zaťaženia z miezd na majetok a environmentálne dane", category: "Ekonomika", isPro: true },
  { text: "Pravidlo tichého súhlasu — ak úrad nerozhodne v lehote, žiadosť je automaticky schválená", category: "Ekonomika", isPro: true },
  { text: "Princíp One-in, One-out — za každú novú reguláciu musí jedna stará zaniknúť", category: "Ekonomika", isPro: true },
  { text: "Zrýchlenie stavebných konaní cez digitalizáciu a zníženie počtu vyjadreni", category: "Ekonomika", isPro: true },
  { text: "Záväzné výdavkové limity pre štátny rozpočet proti zadlžovaniu budúcich generácií", category: "Ekonomika", isPro: true },
  { text: "Investície podľa Hodnoty za peniaze — každý štátny projekt musí prejsť odborným posúdením", category: "Ekonomika", isPro: true },
  { text: "Podpora rizikového kapitálu a vznik súkromných investičných fondov pre startupy", category: "Ekonomika", isPro: true },
  { text: "Digitálne víza pre špičkových expertov a inovátorov zo zahraničia", category: "Ekonomika", isPro: true },
  { text: "Reforma štátnych podnikov — profesionálny manažment bez politických vplyvov", category: "Ekonomika", isPro: true },
  { text: "Priame eurofondy pre regióny — rozhodovanie presunúť na mestá a kraje", category: "Ekonomika", isPro: true },
  { text: "Zelená transformácia priemyslu — stimuly firmám na prechod k ekologickej výrobe", category: "Ekonomika", isPro: true },
  { text: "Ústavna ochrana 2. dôchodkového piliera — nedotknuteľnosť úspor občanov", category: "Ekonomika", isPro: true },
  { text: "Nadstranícky investičný plán výstavby infraštruktúry na 10 rokov", category: "Ekonomika", isPro: true },
  { text: "Štát v mobile (e-Government) — digitalizácia všetkých bežných životných situácií", category: "Ekonomika", isPro: true },
  { text: "Automatizované systémy na odhaľovanie predražených verejných nákupov", category: "Ekonomika", isPro: true },
  { text: "Podpora malých a stredných podnikov — zjednodušenie prístupu k zákazkám a exportným úverom", category: "Ekonomika", isPro: true },
  { text: "Energetická nezávislosť — masívna podpora domácich obnoviteľných zdrojov", category: "Ekonomika", isPro: true },
  { text: "Audit štátneho majetku — predaj nepotrebných budov a investície do inovácií", category: "Ekonomika", isPro: true },
  // Zdravotníctvo (20)
  { text: "Garancia maximálnych čakacích lehôt — preplatenie liečby u iného lekára ak štát neposkytne včas", category: "Zdravotníctvo", isPro: true },
  { text: "Jednotný online rezervačný systém na objednávanie k lekárovi bez skrytých poplatkov", category: "Zdravotníctvo", isPro: true },
  { text: "Posilnenie kompetencií všeobecných lekárov — viac vyriešiť u jedného lekára", category: "Zdravotníctvo", isPro: true },
  { text: "Modernizácia nemocničnej siete — obnova budov a špičková technika z Plánu obnovy", category: "Zdravotníctvo", isPro: true },
  { text: "Stabilizácia počtu sestier — motivačné príplatky a lepšie pracovné podmienky", category: "Zdravotníctvo", isPro: true },
  { text: "Jasné cesty pacienta — manažment pacienta, aby každý vedel kam ísť a čo ho čaká", category: "Zdravotníctvo", isPro: true },
  { text: "Masívna podpora prevencie — zvýšené úhrady za preventívne prehliadky a včasný záchyt onkológie", category: "Zdravotníctvo", isPro: true },
  { text: "Dostupnosť duševného zdravia — viac psychológov v školách a terapie z verejného poistenia", category: "Zdravotníctvo", isPro: true },
  { text: "Centrálne nákupy liekov — efektívnejšie a lacnejšie, úspora stoviek miliónov eur", category: "Zdravotníctvo", isPro: true },
  { text: "Transparentné rebríčky kvality nemocníc — zverejnenie úspešnosti liečby", category: "Zdravotníctvo", isPro: true },
  { text: "Holdingové riadenie štátnych nemocníc s odborným manažmentom", category: "Zdravotníctvo", isPro: true },
  { text: "Program SeniorTech — monitoring zdravia seniorov priamo v ich domovoch", category: "Zdravotníctvo", isPro: true },
  { text: "Prepojenie sociálnej a zdravotnej starostlivosti pre seniorov v jednom balíku", category: "Zdravotníctvo", isPro: true },
  { text: "Elektronizácia zdravotníctva (eZdravie) — okamžitý prístup lekárov k anamnéze pacienta", category: "Zdravotníctvo", isPro: true },
  { text: "Rozšírenie domácej ošetrovateľskej starostlivosti — podpora agentúr ADOS", category: "Zdravotníctvo", isPro: true },
  { text: "Zníženie doplatkov za lieky — efektívnejšia kategorizácia pre lepšiu finančnú dostupnosť", category: "Zdravotníctvo", isPro: true },
  { text: "Investície do lekárskych fakúlt — zvýšenie kapacít pre slovenských študentov medicíny", category: "Zdravotníctvo", isPro: true },
  { text: "Prísne štandardy čistoty a stravy v nemocniciach", category: "Zdravotníctvo", isPro: true },
  { text: "Oficiálny informačný portál overených medicínskych informácií pre občanov", category: "Zdravotníctvo", isPro: true },
  { text: "Rozvoj telemedicíny — legislatíva a úhrady pre online konzultácie s odborníkmi", category: "Zdravotníctvo", isPro: true },
  // Školstvo (20)
  { text: "Reforma učebných osnov — od memorovania k rozvoju kritického myslenia", category: "Školstvo", isPro: true },
  { text: "Zvýšenie atraktívity učiteľského povolania — konkurencieschopné platy a lepšia podpora", category: "Školstvo", isPro: true },
  { text: "Sloboda pre učiteľov — možnosť učiť inovatívnejšie a flexibilnejšie", category: "Školstvo", isPro: true },
  { text: "Inkluzívne vzdelávanie — dostatok asistentov pre deti so špeciálnymi potrebami", category: "Školstvo", isPro: true },
  { text: "Garantované miesto v škôlke pre každé dieťa od 3 rokov", category: "Školstvo", isPro: true },
  { text: "Financovanie univerzít podľa reálnych výsledkov a uplatnenia študentov", category: "Školstvo", isPro: true },
  { text: "Vznik excelentného výskumného centra priťahujúceho vedcov zo sveta", category: "Školstvo", isPro: true },
  { text: "Duálne vzdelávanie 2.0 — prepojenie škôl s modernymi firmami v inovatívnych odvetviach", category: "Školstvo", isPro: true },
  { text: "Program Návrat talentov — podmienky pre mladých Slovákov na návrat po štúdiu v cudzine", category: "Školstvo", isPro: true },
  { text: "Výučba finančnej a mediálnej gramotnosti — príprava na digitálny svet a hoaxy", category: "Školstvo", isPro: true },
  { text: "Digitálne školy — moderné technológie a vysokorýchlostný internet v každej triede", category: "Školstvo", isPro: true },
  { text: "Zjednodušenie uznávania diplomov zo zahraničia", category: "Školstvo", isPro: true },
  { text: "Vzdelávacie vouchery pre dospelých — podpora celoživotného vzdelávania a rekvalifikácie", category: "Školstvo", isPro: true },
  { text: "Projektové vyučovanie o klíme — environmentálne témy ako súčasť praktickej výučby", category: "Školstvo", isPro: true },
  { text: "Navýšenie počtov školských psychológov a špeciálnych pedagógov", category: "Školstvo", isPro: true },
  { text: "Zníženie administratívy riaditeľov — sústredenie na kvalitu výučby", category: "Školstvo", isPro: true },
  { text: "Reforma pedagogických fakúlt podľa najmodernejších svetových trendov", category: "Školstvo", isPro: true },
  { text: "Medzinárodné mobility — rozšírenie výmenných pobytov pre žiakov stredných škôl", category: "Školstvo", isPro: true },
  { text: "AI ako osobný tutor — umelá inteligencia na prispôsobenie tempa výučby každému žiakovi", category: "Školstvo", isPro: true },
  { text: "Pravidelné meranie spokojnosti žiakov a rodičov pre neustále zlepšovanie škôl", category: "Školstvo", isPro: true },
  // Bezpečnosť a právny štát (20)
  { text: "Nezávislosť vyšetrovania — polícia a prokuratúra bez politických zásahov", category: "Bezpečnosť", isPro: true },
  { text: "Rýchlejšie súdy — skrátenie sporov cez digitalizáciu a špecializáciu sudcov", category: "Bezpečnosť", isPro: true },
  { text: "Boj proti hybridným hrozbám — ochrana pred dezinformáciami a kyberútokmi", category: "Bezpečnosť", isPro: true },
  { text: "Kybernetická bezpečnosť štátu — ochrana kritickej infraštruktúry a dát občanov", category: "Bezpečnosť", isPro: true },
  { text: "Efektívna modernizácia armády — 2 % HDP na obranu s transparentnými nákupmi", category: "Bezpečnosť", isPro: true },
  { text: "Reforma policajného zboru — viac policajtov v uliciach, scivilnenie administratívnych pozícií", category: "Bezpečnosť", isPro: true },
  { text: "Ochrana oznamovateľov korupcie — posilnenie inštitúcií chrániacich whistleblowerov", category: "Bezpečnosť", isPro: true },
  { text: "Moderné väzenstvo — resocializácia, aby sa prepustení väzni nevracali ku kriminalite", category: "Bezpečnosť", isPro: true },
  { text: "Krízové riadenie 21. storočia — modernizácia civilnej ochrany pre prípad katastrof", category: "Bezpečnosť", isPro: true },
  { text: "Rovnosť pred zákonom — garancia ochrany ľudských práv pre všetkých bez rozdielu", category: "Bezpečnosť", isPro: true },
  { text: "Transparentné verejné nákupy — každé euro na bezpečnosť pod verejnou kontrolou", category: "Bezpečnosť", isPro: true },
  { text: "Boj proti domácemu násiliu — rozšírenie siete bezpečných ženských domovov", category: "Bezpečnosť", isPro: true },
  { text: "Stabilita v NATO — upevnenie pozície spoľahlivého spojenca v kolektívnej obrane", category: "Bezpečnosť", isPro: true },
  { text: "Vzdelávanie bezpečnostných zložiek — dôraz na etiku a moderné technológie", category: "Bezpečnosť", isPro: true },
  { text: "Ochrana pred ekokriminalitou — prísne tresty za nelegálne skládky a výruby lesov", category: "Bezpečnosť", isPro: true },
  { text: "Profesionálne tajné služby — prísna parlamentná kontrola a apolitickosť", category: "Bezpečnosť", isPro: true },
  { text: "Digitalizácia trestného konania — elektronický spis pre rýchlejšie vyšetrovanie", category: "Bezpečnosť", isPro: true },
  { text: "Podpora komunitnej polície — policajti v teréne s dôrazom na prevenciu", category: "Bezpečnosť", isPro: true },
  { text: "Ochrana novinárov — bezpečné prostredie pre investigatívnu prácu a kontrolu moci", category: "Bezpečnosť", isPro: true },
  { text: "Sanácia infraštruktúry pre obranu — oprava mostov a ciest pre obranné presúvanie", category: "Bezpečnosť", isPro: true },
  // Zahraničná politika (20)
  { text: "Čitateľnosť v EÚ a NATO — spoľahlivý partner ctiaci spoločné dohody a hodnoty", category: "Zahraničná politika", isPro: true },
  { text: "Aktívne členstvo v EÚ — spoluurčovanie pravidiel v Bruseli, nie pasívne prijímanie", category: "Zahraničná politika", isPro: true },
  { text: "Ekonomická diplomacia — veľvyslanectvá pomáhajú slovenským firmám na svetových trhoch", category: "Zahraničná politika", isPro: true },
  { text: "Podpora obnovy Ukrajiny — zapojenie slovenských podnikov do projektov rekonštrukcie", category: "Zahraničná politika", isPro: true },
  { text: "Znižovanie energetickej závislosti — úplné odstrihnutie od ruských fosílnych palív", category: "Zahraničná politika", isPro: true },
  { text: "Lákanie investícií s vysokou pridanou hodnotou z technologicky vyspelých krajín", category: "Zahraničná politika", isPro: true },
  { text: "Strategická komunikácia štátu — aktívna ochrana informačného priestoru pred propagandou", category: "Zahraničná politika", isPro: true },
  { text: "Podpora slovenskej vedy — zapojenie univerzít do elitných európskych výskumných sietí", category: "Zahraničná politika", isPro: true },
  { text: "Ochrana vonkajších hraníc — podpora spoločných európskych riešení migrácie a bezpečnosti", category: "Zahraničná politika", isPro: true },
  { text: "Slovensko ako inovačný lídri V4 v digitálnej a zelenej transformácii regiónu", category: "Zahraničná politika", isPro: true },
  { text: "Znižovanie byrokracie v EÚ — presadzovanie zjednodušenia pravidiel pre malé podniky", category: "Zahraničná politika", isPro: true },
  { text: "Podpora ľudských práv — Slovensko ako hlas utláčaných v medzinárodných organizáciách", category: "Zahraničná politika", isPro: true },
  { text: "Kybernetická diplomacia — líderstvo v bezpečnosti nových technológií a AI", category: "Zahraničná politika", isPro: true },
  { text: "Prezentácia slovenskej kultúry — diplomacia na zviditeľnenie umenia a talentov", category: "Zahraničná politika", isPro: true },
  { text: "Zjednodušenie mobility pre študentov — globálne výmenné programy", category: "Zahraničná politika", isPro: true },
  { text: "Stabilita v susedstve — podpora integračných ambícií krajín západného Balkánu", category: "Zahraničná politika", isPro: true },
  { text: "Boj proti klimatickej kríze — líderstvo v napĺňaní Parížskej dohody v regióne", category: "Zahraničná politika", isPro: true },
  { text: "Modernizácia konzulárnych služieb a pomoci slovenským občanom v cudzine", category: "Zahraničná politika", isPro: true },
  { text: "Rozvojová spolupráca zameraná na stabilizáciu migračných tokov", category: "Zahraničná politika", isPro: true },
  { text: "Posilnenie bezpečnosti dodavateľských reťazcov — preferencia partnerov z demokratických krajín", category: "Zahraničná politika", isPro: true },
  // Sociálne veci (20)
  { text: "Masívna výstavba nájomných bytov — štátny fond dostupného bývania pre mladých", category: "Sociálne veci", isPro: true },
  { text: "Adresná sociálna pomoc — peniaze pre núdznych, nie plošné balíčky pre bohatých", category: "Sociálne veci", isPro: true },
  { text: "Ústavna ochrana úspor v 2. pilieri pred politickými zásahmi", category: "Sociálne veci", isPro: true },
  { text: "Moderné sociálne služby (SeniorTech) — technológie na monitoring zdravia seniorov doma", category: "Sociálne veci", isPro: true },
  { text: "Odstraňovanie generačnej chudoby — vzdelávanie a integrácia detí z vylúčených komunít", category: "Sociálne veci", isPro: true },
  { text: "Podpora zlaďovania práce a rodiny — rozšírenie kapacít jaslí a zdieľané pracovné miesta", category: "Sociálne veci", isPro: true },
  { text: "Zvýšenie príspevku na opatrovanie — dôstojné peniaze pre rodinných opatrovateľov", category: "Sociálne veci", isPro: true },
  { text: "Dostupné nájomné bývanie pre seniorov — malometrážne komunitné byty", category: "Sociálne veci", isPro: true },
  { text: "Rekvalifikácia pre digitálnu dobu — pomoc ľuďom ohrozeným automatizáciou", category: "Sociálne veci", isPro: true },
  { text: "Integrácia marginalizovaných skupín — podpora sociálnych podnikov v regiónoch", category: "Sociálne veci", isPro: true },
  { text: "Boj proti domácemu násiliu — viac bezpečných ženských domovov a rýchlejšia právna ochrana", category: "Sociálne veci", isPro: true },
  { text: "Adresný daňový bonus reálne pomáhajúci nízkoprijmovým pracujúcim rodičom", category: "Sociálne veci", isPro: true },
  { text: "Bezbariérové Slovensko — odstránenie prekážok vo verejných budovách a doprave", category: "Sociálne veci", isPro: true },
  { text: "Zjednodušenie vybavovania dávok online cez jednu aplikáciu (Social e-Gov)", category: "Sociálne veci", isPro: true },
  { text: "Podpora dobrovoľníctva — daňové úľavy a podpora pre komunitné projekty", category: "Sociálne veci", isPro: true },
  { text: "Zníženie regionálnych rozdielov — cielené investície v najmenej rozvinutých okresoch", category: "Sociálne veci", isPro: true },
  { text: "Ochrana zamestnancov v platformovej ekonomike — férové podmienky pre prácu cez aplikácie", category: "Sociálne veci", isPro: true },
  { text: "Rozvoj striebornej ekonomiky — služby a produkty prispôsobené seniorom", category: "Sociálne veci", isPro: true },
  { text: "Prevencia zadlžovania — bezplatné dlhové poradenstvo v každom kraji", category: "Sociálne veci", isPro: true },
  { text: "Kvalitná strava v sociálnych zariadeniach — prísne normy kvality pre domovy dôchodcov", category: "Sociálne veci", isPro: true },
];

export const KNK_PROGRAM_NAME = "Kladivo na korupciu";

// Zdroj: progresivne.sk/kladivo-na-korupciu (aktualizované 11.3.2026)
// 30 avizovaných opatrení, zatiaľ publikovaných 7
export const KNK_PROMISES: PartyPromise[] = [
  // Pilier 1: Koniec „našich ľudí"
  { text: "Najvyššie tresty za korupciu na najvyšších miestach — prísnejšie sadzby pre členov vlády, poslancov a šéfov bezpečnostných zložiek", category: "Koniec našich ľudí", isPro: true },
  { text: "Vyššie tresty politikom za nepriznanie majetku — povinný výpis z katastra doma aj v zahraničí", category: "Koniec našich ľudí", isPro: true },
  { text: "Stop obžalovaným vo vrcholových funkciách — obžalovaný z korupcie nemôže viesť parlament ani výbory", category: "Koniec našich ľudí", isPro: true },
  { text: "Kriminalita sa bude opäť trestať — vyššie tresty, dlhšie premlčacie lehoty a obmedzenie paragrafu 363", category: "Koniec našich ľudí", isPro: true },
  // Pilier 2: Zlodeji musia vrátiť nakradnuté
  { text: "Za korupciu trest a vrátiť nakradnuté aj s úrokmi — firmy vrátia celý zisk zo zákazky získanej úplatkom", category: "Vrátenie nakradnutého", isPro: true },
  { text: "Ochrana oznamovateľov korupcie — posilnenie Úradu na ochranu oznamovateľov korupcie", category: "Vrátenie nakradnutého", isPro: true },
  // Pilier 3: Ústavná poistka
  { text: "Ústavná poistka — protikorupčný ústavný zákon s ochranou kľúčových inštitúcií a výšky trestov", category: "Ústavná poistka", isPro: true },
];
