name = "polis-scraper"
main = "index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "progressive-tracker-db"
database_id = "3988aa54-17b6-4286-b815-eac8ff6ab636"
